// Static-mode (GitHub Pages) check. Needs BASE, e.g. BASE=http://127.0.0.1:8810/gource-view/
import { chromium } from 'playwright'
import assert from 'node:assert/strict'
const S = process.env.S, BASE = process.env.BASE
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []; page.on('pageerror', e => errors.push(e.message))
const failed = []; page.on('requestfailed', r => { if (!r.url().includes('gravatar')) failed.push(r.url()) })
await page.goto(BASE)
await page.getByRole('button', { name: 'Pause', exact: true }).click({ timeout: 30000 })
const index = await (await page.request.get(`${BASE}data/index.json`)).json()
assert.equal(await page.locator('#repo').inputValue(), index.demos[0].name)
assert.equal(await page.getByLabel('Max commits to load').count(), 1, 'browser histories offer bounded commit limits')
await page.locator('.repo-discovery summary').click()
assert.ok(await page.getByRole('button', { name: 'pallets/flask', exact: true }).count() > 0, 'demo suggestions')
await page.locator('.repo-discovery summary').click()
// trending is a baked file, so it works without a server
await page.getByRole('button', { name: /Trending/ }).click()
const trendingList = page.getByRole('listbox', { name: 'Trending repositories' })
await trendingList.waitFor({ timeout: 10000 })
assert.ok(await trendingList.getByRole('option').count() >= 5, 'baked trending list')
assert.match(await page.locator('.trending-panel').innerText(), /refreshed daily/i)
await page.getByRole('tab', { name: '3 months' }).click()
assert.ok(await trendingList.getByRole('option').count() >= 5, 'quarter window from the search API')
await page.getByRole('tab', { name: 'This week' }).click()
await page.screenshot({ path: `${S}/static-trending.png` })
await page.keyboard.press('Escape')
assert.equal(await trendingList.count(), 0)
// unsupported host → explanatory error, no crash
await page.locator('#repo').fill('https://gitlab.com/example/repo'); await page.getByRole('button', { name: 'Load', exact: true }).click()
await page.getByRole('alert').waitFor({ timeout: 10000 })
assert.match(await page.getByRole('alert').innerText(), /public GitHub repository/)
// a demo loads from JSON
await page.locator('.repo-discovery summary').click()
await page.getByRole('button', { name: 'pallets/flask', exact: true }).click()
await page.getByRole('button', { name: 'Pause', exact: true }).click({ timeout: 30000 })
assert.match(await page.locator('main').innerText(), /flask/)
// export → self-host note; video mode → music from the static files
await page.getByRole('button', { name: 'Export video' }).click()
assert.match(await page.locator('.export-dialog').innerText(), /Self-host/)
await page.keyboard.press('Escape')
await page.getByRole('button', { name: /Video/ }).click()
await page.locator('.video-mode').waitFor()
await page.waitForTimeout(1500)
const src = await page.locator('.video-mode audio').getAttribute('src')
assert.match(src, /\/gource-view\/music\/.*\.mp3$/)
await page.screenshot({ path: `${S}/static-video.png` })
await page.keyboard.press('Escape')
assert.deepEqual(errors, []); assert.deepEqual(failed, [])
console.log('static check ok')
await browser.close()
